"""Original geometric artwork, dedicated CC0-1.0; not device/camera evidence.
Run with Pillow 12.3.0 and pillow-heif 1.8.0 (libheif 1.23.4/x265 4.2).
"""
from pathlib import Path
from PIL import Image, ImageDraw
import pillow_heif, hashlib, json
pillow_heif.register_heif_opener()
root = Path(__file__).resolve().parents[1] / 'tests/fixtures/codecs'
root.mkdir(parents=True, exist_ok=True)
im = Image.new('RGB', (320, 240), 'white')
d = ImageDraw.Draw(im)
d.rectangle((0, 0, 159, 119), fill='red'); d.rectangle((160, 0, 319, 119), fill='green')
d.rectangle((0, 120, 159, 239), fill='blue'); d.rectangle((160, 120, 319, 239), fill='yellow')
for name, kw in [('lossy.webp', {'quality':80}), ('lossless.webp', {'lossless':True}), ('still.avif', {'quality':85})]:
    im.save(root/name, **kw)
im.save(root/'encoded.heic', quality=85)
im.rotate(90, expand=True).save(root/'portrait.heif', quality=85)
alpha=im.convert('RGBA'); alpha.putalpha(128); alpha.save(root/'alpha.webp',lossless=True)
im.save(root/'animated.webp',save_all=True,append_images=[im.rotate(180)],duration=100,loop=0)
im.save(root/'collection.heif',save_all=True,append_images=[im.rotate(180)],quality=85)
# Orientation is passed to real encoders, never baked into the quadrant pixels.
# WebP retains TIFF EXIF; libavif/libheif encode EXIF orientation as irot/imir.
for ext in ['webp', 'avif', 'heif']:
    for label, orientation in [('rotate', 6), ('mirror', 2)]:
        exif = Image.Exif(); exif[274] = orientation
        im.save(root / f'{label}.{ext}', exif=exif.tobytes(), quality=85)
# libwebp emits bare TIFF. Retain the standard Exif preamble for browser interop.
for label in ['rotate', 'mirror']:
    p = root / f'{label}.webp'; b = bytearray(p.read_bytes()); o = b.index(b'EXIF')
    n = int.from_bytes(b[o+4:o+8], 'little'); payload = b[o+8:o+8+n]
    b[o+4:o+8+n+(n%2)] = (n+6).to_bytes(4,'little') + b'Exif\0\0' + payload + (b'\0' if n%2 else b'')
    b[4:8] = (len(b)-8).to_bytes(4,'little'); p.write_bytes(b)
entries=[]
for p in sorted(root.iterdir()):
    if p.suffix not in ['.heic','.heif','.webp','.avif']: continue
    with Image.open(p) as opened:
        entries.append({'transform': ('EXIF orientation 6 (CW90)' if p.stem=='rotate' else 'EXIF orientation 2 (horizontal mirror)') if p.suffix=='.webp' and p.stem in ['rotate','mirror'] else ('irot=3 (CW90)' if p.stem=='rotate' else 'imir horizontal') if p.stem in ['rotate','mirror'] else 'none (portrait has baked pixels)', 'encodedSize': [320,240] if p.stem in ['rotate','mirror'] else list(opened.size), 'displaySize': [240,320] if p.stem=='rotate' else list(opened.size), 'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'size':list(opened.size),'frames':getattr(opened,'n_frames',1),'license':'CC0-1.0','source':'Original quadrant artwork generated by scripts/generate-codec-fixtures.py; no device provenance','encoder':'Pillow 12.3.0; HEVC: pillow-heif 1.8.0/libheif 1.23.4/x265 4.2+1; WebP: Pillow libwebp; AVIF: Pillow libavif'})
(root/'manifest.json').write_text(json.dumps(entries,indent=2)+'\n')
