"""Original geometric artwork, dedicated CC0-1.0; not device/camera evidence.
Run with Pillow 12.3.0 and pillow-heif 1.8.0 (libheif 1.23.4/x265 4.2).
"""
from pathlib import Path
from PIL import Image, ImageDraw
import pillow_heif, hashlib, json
pillow_heif.register_heif_opener()
root = Path(__file__).resolve().parents[1] / 'tests/fixtures/codecs'
root.mkdir(parents=True, exist_ok=True)
im = Image.new('RGB', (320, 240), 'white')
d = ImageDraw.Draw(im)
d.rectangle((0, 0, 159, 119), fill='red'); d.rectangle((160, 0, 319, 119), fill='green')
d.rectangle((0, 120, 159, 239), fill='blue'); d.rectangle((160, 120, 319, 239), fill='yellow')
for name, kw in [('lossy.webp', {'quality':80}), ('lossless.webp', {'lossless':True}), ('still.avif', {'quality':85})]:
    im.save(root/name, **kw)
im.save(root/'encoded.heic', quality=85)
im.rotate(90, expand=True).save(root/'portrait.heif', quality=85)
alpha=im.convert('RGBA'); alpha.putalpha(128); alpha.save(root/'alpha.webp',lossless=True)
im.save(root/'animated.webp',save_all=True,append_images=[im.rotate(180)],duration=100,loop=0)
im.save(root/'collection.heif',save_all=True,append_images=[im.rotate(180)],quality=85)
entries=[]
for p in sorted(root.iterdir()):
    if p.suffix not in ['.heic','.heif','.webp','.avif']: continue
    with Image.open(p) as opened:
        entries.append({'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'size':list(opened.size),'frames':getattr(opened,'n_frames',1),'license':'CC0-1.0','source':'Original quadrant artwork generated by scripts/generate-codec-fixtures.py; no device provenance','encoder':'Pillow 12.3.0; HEVC: pillow-heif 1.8.0/libheif 1.23.4/x265 4.2+1; WebP: Pillow libwebp; AVIF: Pillow libavif'})
(root/'manifest.json').write_text(json.dumps(entries,indent=2)+'\n')
