import {test,expect,vi,afterEach} from 'vitest';
import {readFileSync} from 'node:fs';
import {loadImage} from '../../src/lib/image/load';
import {normalizeBitmap} from '../../src/lib/image/heic';
vi.mock('https://cdn.jsdelivr.net/npm/heic-to@1.6.5/dist/csp/heic-to.js',()=>({heicTo:vi.fn()}));
const {heicTo}=await import(/* @vite-ignore */ String('https://cdn.jsdelivr.net/npm/heic-to@1.6.5/dist/csp/heic-to.js')) as typeof import('heic-to/csp');
const file=(n:string)=>new File([readFileSync(`tests/fixtures/codecs/${n}`)],n);
const bitmap=(w=320,h=240)=>({width:w,height:h,close:vi.fn()}) as unknown as ImageBitmap;
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();});
test('HEIF native failure invokes fallback once; normalized output disposes once',async()=>{const b=bitmap();vi.stubGlobal('createImageBitmap',vi.fn().mockRejectedValue(new Error('native')));vi.mocked(heicTo).mockImplementation(()=>Promise.resolve(b as never));const result=await loadImage(file('encoded.heic'));expect(heicTo).toHaveBeenCalledTimes(1);result.dispose();result.dispose();expect(b.close).toHaveBeenCalledTimes(1);});
test('native success does not load HEVC fallback',async()=>{vi.stubGlobal('createImageBitmap',vi.fn().mockResolvedValue(bitmap()));await loadImage(file('encoded.heic'));expect(heicTo).not.toHaveBeenCalled();});
test('AVIF failure never invokes HEVC',async()=>{vi.stubGlobal('createImageBitmap',vi.fn().mockRejectedValue(new Error('native')));await expect(loadImage(file('still.avif'))).rejects.toThrow();expect(heicTo).not.toHaveBeenCalled();});
test('modern HTML fallback sizes from real display and does not retry bitmap',async()=>{
 const decode=vi.fn().mockRejectedValue(new Error('native'));vi.stubGlobal('createImageBitmap',decode);
 const draw=vi.fn(),canvas={width:0,height:0,getContext:()=>({drawImage:draw})};
 vi.stubGlobal('Image',class {naturalWidth=240;naturalHeight=320;onload:(()=>void)|null=null;onerror=null;set src(value:string){if(value)queueMicrotask(()=>this.onload?.());}});
 vi.stubGlobal('document',{createElement:()=>canvas});vi.stubGlobal('URL',{createObjectURL:vi.fn(()=> 'blob:test'),revokeObjectURL:vi.fn()});
 const result=await loadImage(file('rotate.avif'));expect(result.size).toEqual({width:240,height:320});expect(decode).toHaveBeenCalledTimes(1);expect(draw).toHaveBeenCalledWith(expect.anything(),0,0,240,320);result.dispose();expect(canvas.width).toBe(0);
});
test('normalized original bitmap owns full pixels and disposes once; zero bitmap fails',async()=>{const full=bitmap(8000,6000);const decode=vi.fn();vi.stubGlobal('createImageBitmap',decode);const result=await normalizeBitmap(full);expect(result.size).toEqual({width:8000,height:6000});expect(result.source).toBe(full);expect(decode).not.toHaveBeenCalled();expect(full.close).not.toHaveBeenCalled();result.dispose();result.dispose();expect(full.close).toHaveBeenCalledTimes(1);const zero=bitmap(0,0);await expect(normalizeBitmap(zero)).rejects.toThrow();expect(zero.close).toHaveBeenCalledTimes(1);});
test('only one native decode executes while another load is pending',async()=>{let resolve!:(b:ImageBitmap)=>void;const first=new Promise<ImageBitmap>(r=>resolve=r);const decode=vi.fn().mockReturnValueOnce(first).mockResolvedValue(bitmap());vi.stubGlobal('createImageBitmap',decode);const a=loadImage(file('lossy.webp'));await vi.waitFor(()=>expect(decode).toHaveBeenCalledTimes(1));const b=loadImage(file('still.avif'));await new Promise(r=>setTimeout(r,20));expect(decode).toHaveBeenCalledTimes(1);resolve(bitmap());(await a).dispose();(await b).dispose();expect(decode).toHaveBeenCalledTimes(2);});
